spring:
  datasource:
    url: "jdbc:mysql://8.142.15.149:3306/computersshop?useUnicode=true&serverTimezone=GMT&characterEncoding=utf8&useSSL=true"
    username: computersShop
    password: RdBpKAshBxzt28nF
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
  main:
    allow-circular-references: true
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
server:
  port: 3100

spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
