spring:
  datasource:
    url: "jdbc:mysql://8.142.15.149:3306/computersshop?useUnicode=true&serverTimezone=GMT&characterEncoding=utf8&useSSL=true"
    username: computersShop
    password: RdBpKAshBxzt28nF
mybatis:
  mapper-locations: "classpath:mapper/*.xml"
server:
  port: 3100
